version: "3.9"

services:
  minio:
    image: minio/minio:RELEASE.2023-05-27T05-56-19Z
    restart: always
    stop_grace_period: 10s
    working_dir: /data
    volumes:
      - minio-data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: user
      MINIO_SECRET_KEY: password
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
      MINIO_STORAGE_USE_HTTPS: False
      MINIO_PROMETHEUS_AUTH_TYPE: public
    command: server --console-address :9001 --address :9000 /data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    command: start-dev

  mc:
    image: minio/mc:RELEASE.2023-05-30T22-41-38Z
    environment:
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: user
      MINIO_SECRET_KEY:
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c ' sleep 5; /usr/bin/mc config host add s3 http://minio:9000 user password --api S3v4; [[ ! -z "`/usr/bin/mc ls s3 | grep challenge`" ]] || /usr/bin/mc mb s3/mlflow;  /usr/bin/mc policy download s3/mlflow; [[ ! -z "`/usr/bin/mc ls s3 | grep challenge`" ]] || /usr/bin/mc mb s3/data;  /usr/bin/mc policy download s3/data; exit 0; '

networks:
  default:
    name: keycloak_flask

volumes:
  minio-data: {}
  ingestion-volume-dag-airflow: {}
  ingestion-volume-dags: {}
  ingestion-volume-tmp: {}
  es-data: {}
  db-data-postgres: {}
